version: "3.8"

services:
  db:
    image: postgres:14
    container_name: smarttodo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smarttodo
      POSTGRES_USER: anmol
      POSTGRES_PASSWORD: secret123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
